version: "3.7"
services:
  golem.container:
    container_name: developer_golem_container
    platform: linux/x86_64
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ../dist/release:/entrypoint
    environment:
      DEBUG: 1
      AWS_REGION: us-east-1
      CLOUD_PROVIDER: local
      GOLEM_ENVIRONMENT: local
      GOLEM_STACK: development
      GOLEM_SERVICE: developer_service
      PROC_TYPE: ssh
      SSH_PORT: 22
      AUTHORIZED_PUBLIC_KEY: "${AUTHORIZED_PUBLIC_KEY}"
      SSH_ORIGINAL_COMMAND: "${SSH_ORIGINAL_COMMAND}"
      UNLOCK_ROOT: "${UNLOCK_ROOT}"
    ports:
      - "1122:22"
